config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :chat_rooms, only: [:index, :show]
    end
  end

  devise_for :users

  resources :chat_rooms, only: [:index, :new, :create, :show] do
    resources :messages, only: [:create]
  end

  resource :user, only: [:show, :edit, :update]

  root "chat_rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum membership: { Standard: 0, Premium: 1 }

  validates :email, uniqueness: true
  validates :username, uniqueness: true
  before_create :set_username

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  private

  def set_username
    self.username = self.email.split('@')[0]
  end

end

app/controllers/api/v1/chat_rooms_controller.rb
class Api::V1::ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.includes(:messages).all
    render json: @chat_rooms, include: ['messages'], status: :ok
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find(params[:id])
    render json: @chat_room, include: ['messages'], status: :ok
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'ChatRoom not found' }, status: :not_found
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all
    render json: @users, status: :ok and return
  end

  def show
    @user = User.find(params[:id])
    render json: @user, status: :ok
    rescue ActiveRecord::RecordNotFound
      render json: { error: 'User not found' }, status: :not_found
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "No authorization. Check your membership in the Profile tab."
    redirect_to(root_path)
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authorize_chat_room, only: [:show]

  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    authorize @chat_room

      if @chat_room.save
        redirect_to @chat_room
      else
        render :new
      end
  end

  def show
    set_chat_room
    @message = Message.new
    @messages = @chat_room.messages.all
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:name)
  end

  def set_chat_room
    @chat_room = ChatRoom.find(params[:id])
  end

  def authorize_chat_room
    set_chat_room
    authorize @chat_room
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @message = @chat_room.messages.build(message_params)
    @message.user = current_user

    if @message.save
      ChatRoomChannel.broadcast_to(@chat_room, {
        content: @message.content,
        user_email: @message.user.email,
        username: @message.user.username
      })
      head :ok
    else
      @messages = @chat_room.messages.order(created_at: :desc)
      render "chat_rooms/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile updated successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:membership)
  end
end

app/helpers/api/v1/chat_rooms_helper.rb
module Api::V1::ChatRoomsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/index.html.erb
<div class="min-h-screen">
  <h1 class="font-bold text-5xl text-center mt-8">
    Chat Rooms
  </h1>
  <div>
    <ul>
      <% @chat_rooms.each do |chat_room| %>
        <li class="border-2 rounded-lg mt-12 w-2/3 mx-auto hover:border-sky-800 relative">
          <%= link_to chat_room.name, chat_room, class: "p-8 block font-semibold text-xl" %>
          <span class="absolute right-0 bottom-0 px-4 pb-4">
            <b>Administrator: </b> <%= chat_room.user.username %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/chat_rooms/new.html.erb
<div class="flex flex-col items-center h-screen">
  <h1 class="text-5xl font-bold">
    New Chat Room
  </h1>
  <div class="mt-16">
    <%= form_with model: @chat_room do |form| %>
    <%= form.label :name, class: "font-medium text-lg" %>: 
    <%= form.text_field :name %>
    <%= form.submit 'Create Room',
      class: "text-white bg-blue-700 font-medium text-sm px-12 py-2 text-center ml-8 cursor-pointer hover:bg-blue-500" %>
    <% end %>
  </div>
</div>

app/views/chat_rooms/show.html.erb
<div class="min-h-screen">

  <h2 class="font-bold text-center text-5xl">
    <%= @chat_room.name %>
  </h2>

  <input type="hidden" id="current_user_email" value="<%= current_user.email %>">

  <div id="message-container" data-chat-room-id="<%= @chat_room.id %>"
    class="mt-12 mx-auto no-scrollbar border-2 rounded-3xl w-2/3 h-96 overflow-y-scroll bg-sky-50">
      <% @messages.each do |message| %>
        <div id="message"
          is-current-user="<%= message.user.email %>"
          class="<%= message.user == current_user ? 'text-right' : 'text-left'%> py-4 px-8 "
        >
            <p class="font-bold text-xs">
              <%= message.user.username %>
            </p>
            <p class="text-xs text-gray">
              <%= message.created_at.in_time_zone('Istanbul').strftime("%d %B, %H:%M") %>
            </p>
            <p class="text-lg font-medium py-1 text-black">
              <%= message.content %>
            </p>
        </div>
      <% end %>
  </div>

<div class="w-2/3 mt-12 mx-auto">
  <%= form_with model: [@chat_room, Message.new],
    url: chat_room_messages_path(@chat_room), remote: true do |form| %>
    <%= form.text_field :content, id: "text-field",
      class: "w-11/12 rounded-full px-6", placeholder: "Type your message..."
    %>
    <%= form.submit 'Send',
      class: "text-white bg-blue-700 font-medium rounded-full text-sm px-5 py-2.5 text-center cursor-pointer"
    %>
  <% end %>
</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="w-screen h-screen text-gray-800 overflow-x-hidden">
    <%= render 'shared/navbar' %>
    <main class="container mx-auto w-11/12">
      <%= render 'shared/flash' %>
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="text-center my-16 font-semibold text-2xl">
  <% ["notice", "alert"].each do |message_type| %>
    <% if flash[message_type.to_sym].present? %>
      <p style="color: <%= message_type == 'notice' ? 'green' : 'red' %>; font-weight: bold;" 
         data-controller="close-message" 
         data-action="click->close-message#close">
        <%= flash[message_type.to_sym] %>
        <span class="cursor-pointer text-gray-500 mr-4 hover:text-gray-700">
          X
        </span>
      </p>
    <% end %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-sky-100 py-4 mt-24">

  <div class="flex justify-between mx-12">
    <p> &copy; 2024 Chat App</p>
    <p>iWallet Kurumsal Hizmetler A.Ş</p>
    <div>
      <%= link_to "https://www.linkedin.com/in/sametpolat17/",
      target: "_blank", rel: "noopener noreferrer" do %>
        <%= image_tag "linkedin.svg", alt: "LinkedIn",
        class: "inline-block w-6 h-6 mr-4" %>
      <% end %>
      <%= link_to "https://github.com/sametpolat7",
      target: "_blank", rel: "noopener noreferrer" do %>
        <%= image_tag "github.svg", alt: "GitHub",
        class: "inline-block w-6 h-6" %>
      <% end %>
    </div>
  </div>
  
</footer>

app/views/shared/_navbar.html.erb
<nav class="flex justify-between items-center bg-sky-50 h-16 fixed w-full top-0 z-10 p-8">
  <%= link_to "ChatApp", chat_rooms_path, class: "font-bold text-4xl" %>
  <div>
    <% if current_user %>
      <div class="flex font-semibold text-lg">
        <%= link_to  "Chat Rooms", chat_rooms_path, class: "mx-8 hover:font-bold" %>
        |
        <%= link_to 'New Chat Room', new_chat_room_path, class: "mx-8 hover:font-bold" %>
        |
        <%= link_to "Profile", user_path, class: "mx-8 hover:font-bold" %>
        |
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "ml-8 hover:font-bold" %>
      </div>
    <% else %>
      <div class="font-semibold">
        <%= link_to "Login", new_user_session_path, class: "mr-8 hover:font-bold" %>
        |
        <%= link_to "Sign up", new_user_registration_path, class: "ml-8 hover:font-bold" %>
      </div>
    <% end %>
  </div>
</nav>
<div class="pt-20"></div>

app/views/users/edit.html.erb
<div class="flex flex-col items-center min-h-screen">
  <h2 class="text-4xl font-semibold text-center">
    Edit Profile
  </h2>
  <%= form_with model: @user, url: user_path, method: :put do |form| %>
    <div class="mt-16">
      <%= form.label :membership %>: 
      <%= form.select :membership, User.memberships.keys.map { |membership| [membership.humanize, membership] }%>
          <%= form.submit 'Update',
      class: "text-white bg-blue-700 font-medium text-sm px-12 py-2 text-center ml-8 cursor-pointer hover:bg-blue-500"
    %>
    </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="min-h-screen">
  <h2 class="font-bold text-5xl text-center">
      <%= current_user.username %>'s Profile
  </h2>
  <div class="flex justify-between mt-32">
    <div class="w-1/2">
      <p class="font-medium text-lg">
        <strong>Email: </strong>
        <%= current_user.email %>
      </p>
      <br>
      <p class="font-medium text-lg">
        <strong>Username: </strong>
        <%= current_user.username %>
      </p>
      <br>
      <p class="font-medium text-lg">
        <strong>Membership: </strong>
        <%= current_user.membership %>
      </p>
      <br><br>
      <%= link_to 'Change Status', edit_user_path,
        class: "text-white bg-blue-700 font-medium text-sm px-5 py-2.5 text-center ml-4 cursor-pointer hover:bg-blue-500"
      %>
    </div>
    <div class="w-1/2">
      <h2 class="text-center font-medium text-2xl mb-8">
        <%= current_user.username %>'s Rooms
      </h2>
      <% if current_user.chat_rooms.any? %>
        <ul>
        <% @user.chat_rooms.each do |room| %>
          <li>
            <%= link_to room.name, chat_room_path(room),
              class: "p-8 block font-medium text-xl border-2 rounded-lg mb-4 hover:border-sky-800"
            %>
          </li>
        <% end %>
        </ul>
        <% else %>
          <p class="text-center text-lg mt-16">User does not have any room yet.</p>
        <% end %>
    </div>
  </div>
</div>